# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Initialize age
#' @name start_age
NULL

#' Mouth-width-to-length ratio
#' @name start_mouth
NULL

#' Age to length conversion
#' @name age2length
NULL

#' Milk assimilation efficiency
#' @name milk_assimilation
NULL

#' Milk provisioning
#' @name milk_supply
NULL

#' Total mass of mammary glands
#' @name mammary_mass
NULL

#' Milk production rate
#' @name milk_production
NULL

#' Resting metabolic rate
#' @name RMR
NULL

rtnorm <- function(mean, sd, low, high) {
    .Call('_narwind_rtnorm', PACKAGE = 'narwind', mean, sd, low, high)
}

estBetaParams <- function(mu, std) {
    .Call('_narwind_estBetaParams', PACKAGE = 'narwind', mu, std)
}

transpose_c <- function(m, k) {
    .Call('_narwind_transpose_c', PACKAGE = 'narwind', m, k)
}

multinomial <- function(probs) {
    .Call('_narwind_multinomial', PACKAGE = 'narwind', probs)
}

random_int <- function(n, lwr = 0L, uppr = 3L) {
    .Call('_narwind_random_int', PACKAGE = 'narwind', n, lwr, uppr)
}

random_multivariate_normal <- function(mu, Sigma) {
    .Call('_narwind_random_multivariate_normal', PACKAGE = 'narwind', mu, Sigma)
}

prob_migration <- function(n, destination, cohortID) {
    .Call('_narwind_prob_migration', PACKAGE = 'narwind', n, destination, cohortID)
}

response_threshold <- function(dose, day, simduration, seed) {
    .Call('_narwind_response_threshold', PACKAGE = 'narwind', dose, day, simduration, seed)
}

starvation_mortality <- function(bc, coefs, starvation_death, starvation_onset) {
    .Call('_narwind_starvation_mortality', PACKAGE = 'narwind', bc, coefs, starvation_death, starvation_onset)
}

starvation_mortality_vec <- function(bc, coefs, starvation_death, starvation_onset) {
    .Call('_narwind_starvation_mortality_vec', PACKAGE = 'narwind', bc, coefs, starvation_death, starvation_onset)
}

is_female <- function(cohort) {
    .Call('_narwind_is_female', PACKAGE = 'narwind', cohort)
}

start_age <- function(cohort) {
    .Call('_narwind_start_age', PACKAGE = 'narwind', cohort)
}

start_age_vec <- function(cohort) {
    .Call('_narwind_start_age_vec', PACKAGE = 'narwind', cohort)
}

#' Entanglement event
#' @name entanglement_event
#' @param p_head Probability that the entanglement involves the anterior region of the body (mouth, head, rostrum)
entanglement_event <- function(p_entangled = 0, p_head = 0.732, p_severity = as.numeric( c(0.819, 0.140, 0.041))) {
    .Call('_narwind_entanglement_event', PACKAGE = 'narwind', p_entangled, p_head, p_severity)
}

start_mouth <- function(cohort, age) {
    .Call('_narwind_start_mouth', PACKAGE = 'narwind', cohort, age)
}

#' Initialize body condition
#' @name start_bcondition
#' @description Performs a random draw from a beta distribution to initialize 
#' the body condition of simulated animals, taken as the ratio of fat mass to total mass.
#' @param age Age in years
#' @param shape1 First shape parameter of the beta distribution
#' @param shape2 Second shape parameter of the beta distribution
start_bcondition <- function(cohort) {
    .Call('_narwind_start_bcondition', PACKAGE = 'narwind', cohort)
}

#' Initialize body condition 
#' @name start_bcondition_vec
#' @description Performs a random draw from a beta distribution to initialize
#' the body condition of simulated animals, taken as the ration of fat mass to total mass.
#' @param age Age in years
#' @param shape1 First shape parameter of the beta distribution
#' @param shape2 Second shape parameter of the beta distribution
start_bcondition_vec <- function(cohort, month = 10L) {
    .Call('_narwind_start_bcondition_vec', PACKAGE = 'narwind', cohort, month)
}

agL <- function(age, n = 1L, sd = FALSE) {
    .Call('_narwind_agL', PACKAGE = 'narwind', age, n, sd)
}

agL_vec <- function(age, sd = FALSE) {
    .Call('_narwind_agL_vec', PACKAGE = 'narwind', age, sd)
}

age2length <- function(age, gompertz) {
    .Call('_narwind_age2length', PACKAGE = 'narwind', age, gompertz)
}

age2length_vec <- function(age) {
    .Call('_narwind_age2length_vec', PACKAGE = 'narwind', age)
}

mL <- function(n = 1L, sd = FALSE) {
    .Call('_narwind_mL', PACKAGE = 'narwind', n, sd)
}

length2mass <- function(L, param, lean = 0.5554227) {
    .Call('_narwind_length2mass', PACKAGE = 'narwind', L, param, lean)
}

length2mass_vec <- function(L, lean = 0.5435686) {
    .Call('_narwind_length2mass_vec', PACKAGE = 'narwind', L, lean)
}

increment_cohort <- function(alive, cohort, age, female, bc, min_bc, reprod, abort) {
    .Call('_narwind_increment_cohort', PACKAGE = 'narwind', alive, cohort, age, female, bc, min_bc, reprod, abort)
}

#' Incidence of foraging behavior
#' @name feeding_threshold
#' @description Determines whether the prey concentration encountered by an animal
#' is sufficient to support foraging
#' @param min_prey Minimum prey density threshold that triggers foraging 
#' @param D Prey concentration
feeding_threshold <- function(min_prey, prey_concentration) {
    .Call('_narwind_feeding_threshold', PACKAGE = 'narwind', min_prey, prey_concentration)
}

#' Incidence of foraging behavior (vectorized)
#' @name feeding_threshold_vec
#' @description Determines whether the prey concentration encountered by an animal
#' is sufficient to support foraging
#' @param min_prey Minimum prey density threshold that triggers foraging
#' @param D Prey concentration
feeding_threshold_vec <- function(min_prey, prey_concentration) {
    .Call('_narwind_feeding_threshold_vec', PACKAGE = 'narwind', min_prey, prey_concentration)
}

feeding_effort <- function(eta, rho, bc) {
    .Call('_narwind_feeding_effort', PACKAGE = 'narwind', eta, rho, bc)
}

feeding_effort_vec <- function(eta, rho, bc) {
    .Call('_narwind_feeding_effort_vec', PACKAGE = 'narwind', eta, rho, bc)
}

#' Convert degrees to radians
#' @name deg2radians
#' @param angle Input angle in degrees
#' @return Equivalent angle in radians
deg2radians <- function(angle) {
    .Call('_narwind_deg2radians', PACKAGE = 'narwind', angle)
}

#' Area of the gape
#' @name gape_size
#' @description Provides an estimate of the area of the mouth gape
#' @param L Total body length (m)
#' @param omega Width of the mouth (m)
#' @param alpha Angle between the tip of the baleen plates and outer edge of the baleen racks (rad)
#' @note The gape is assumed to be a disk sector defined by the height of the tallest baleen plate 
#' and the width of the mouth. The central angle can be estimated based on 3D models 
#' of right whales and bowhead whales developed from measurements taken during whaling,
#' necropsies, and aerial photogrammetry studies
#' @return Estimated gape area
gape_size <- function(L, omega, alpha) {
    .Call('_narwind_gape_size', PACKAGE = 'narwind', L, omega, alpha)
}

milk_assimilation <- function(t, T_lac, a, zeta) {
    .Call('_narwind_milk_assimilation', PACKAGE = 'narwind', t, T_lac, a, zeta)
}

milk_assimilation_vec <- function(t, T_lac, a, zeta) {
    .Call('_narwind_milk_assimilation_vec', PACKAGE = 'narwind', t, T_lac, a, zeta)
}

milk_supply <- function(kappa, target_condition, M, R, zeta) {
    .Call('_narwind_milk_supply', PACKAGE = 'narwind', kappa, target_condition, M, R, zeta)
}

milk_supply_vec <- function(kappa, target_condition, M, R, zeta) {
    .Call('_narwind_milk_supply_vec', PACKAGE = 'narwind', kappa, target_condition, M, R, zeta)
}

mammary_mass <- function(M) {
    .Call('_narwind_mammary_mass', PACKAGE = 'narwind', M)
}

milk_production <- function(m) {
    .Call('_narwind_milk_production', PACKAGE = 'narwind', m)
}

RMR <- function(M) {
    .Call('_narwind_RMR', PACKAGE = 'narwind', M)
}

#' Costs of locomotion
locomotor_costs <- function(mass, distance, strokerate_foraging, strokerate, glide_foraging, glide, t_feed, t_activ, scalar) {
    .Call('_narwind_locomotor_costs', PACKAGE = 'narwind', mass, distance, strokerate_foraging, strokerate, glide_foraging, glide, t_feed, t_activ, scalar)
}

#' Energetic cost of placental maintenance during pregnancy (vectorised)
#' @name placental_maintenance
#' @param G Energetic cost of fetal growth (kJ)
placental_maintenance_vec <- function(G) {
    .Call('_narwind_placental_maintenance_vec', PACKAGE = 'narwind', G)
}

#' Energetic cost of placental maintenance during pregnancy
#' @name placental_maintenance
#' @param G Energetic cost of fetal growth (kJ)
placental_maintenance <- function(G) {
    .Call('_narwind_placental_maintenance', PACKAGE = 'narwind', G)
}

#' Heat increment of gestation
#' @name heat_gestation
#' @param birth_mass Birth mass of the fetus (kg)
#' @param delta_m Daily growth rate of the fetus (kg/day)
heat_gestation <- function(birth_mass, delta_m) {
    .Call('_narwind_heat_gestation', PACKAGE = 'narwind', birth_mass, delta_m)
}

#' Heat increment of gestation (vectorised)
#' @name heat_gestation
#' @param birth_mass Birth mass of the fetus (kg)
#' @param delta_m Daily growth rate of the fetus (kg/day)
heat_gestation_vec <- function(birth_mass, delta_m) {
    .Call('_narwind_heat_gestation_vec', PACKAGE = 'narwind', birth_mass, delta_m)
}

#' Fetal tissue mass
#' @name fetal_tissue_mass
#' @param P_b Proportion of the body volume comprised of tissue b
#' @param L Length of the fetus (m)
#' @note This relationship only applies to muscles, bones, and viscera
fetal_tissue_mass <- function(P_b, L) {
    .Call('_narwind_fetal_tissue_mass', PACKAGE = 'narwind', P_b, L)
}

#' Fetal tissue mass (vectorised)
#' @name fetal_tissue_mass
#' @param P_b Proportion of the body volume comprised of tissue b
#' @param L Length of the fetus (m)
#' @note This relationship only applies to muscles, bones, and viscera
fetal_tissue_mass_vec <- function(P_b, L) {
    .Call('_narwind_fetal_tissue_mass_vec', PACKAGE = 'narwind', P_b, L)
}

#' Fetal blubber mass
#' @name fetal_blubber_mass
#' @param L Length of the fetus (m)
#' @param M_muscle Mass of muscles in the fetus (kg)
#' @param M_viscera Mass of viscera in the fetus (kg)
#' @param M_bones Mass of bone tissues in the fetus (kg)
#' @param D_blubber Average blubber density (kg/m^3)
#' @param D_muscle Average muscle density (kg/m^3)
#' @param D_viscera Average density of viscera (kg/m^3)
#' @param D_bones Average bone density (kg/m^3)
#' @note The original equation from Christiansen et al. (2022) (DOI: 10.3354/meps14009) includes an additional term
#' designed to account for the calf's body condition at birth. However, Christiansen et al. rely on a metric of body condition (BC)
#' that differs from, and is not readily comparable to, ours. Here, we assume that BC = 0, which corresponds to an animal of average
#' body condition. 
fetal_blubber_mass <- function(L, BC, M_muscle, M_viscera, M_bones, D_blubber, D_muscle, D_viscera, D_bones) {
    .Call('_narwind_fetal_blubber_mass', PACKAGE = 'narwind', L, BC, M_muscle, M_viscera, M_bones, D_blubber, D_muscle, D_viscera, D_bones)
}

#' Fetal blubber mass (vectorised)
#' @name fetal_blubber_mass
#' @param L Length of the fetus (m)
#' @param M_muscle Mass of muscles in the fetus (kg)
#' @param M_viscera Mass of viscera in the fetus (kg)
#' @param M_bones Mass of bone tissues in the fetus (kg)
#' @param D_blubber Average blubber density (kg/m^3)
#' @param D_muscle Average muscle density (kg/m^3)
#' @param D_viscera Average density of viscera (kg/m^3)
#' @param D_bones Average bone density (kg/m^3)
#' @note The original equation from Christiansen et al. (2022) (DOI: 10.3354/meps14009) includes an additional term
#' designed to account for the calf's body condition at birth. However, Christiansen et al. rely on a metric of body condition (BC)
#' that differs from, and is not readily comparable to, ours. Here, we assume that BC = 0, which corresponds to an animal of average
#' body condition. 
fetal_blubber_mass_vec <- function(L, BC, M_muscle, M_viscera, M_bones, D_blubber, D_muscle, D_viscera, D_bones) {
    .Call('_narwind_fetal_blubber_mass_vec', PACKAGE = 'narwind', L, BC, M_muscle, M_viscera, M_bones, D_blubber, D_muscle, D_viscera, D_bones)
}

#' Fetal mass 
#' @name fetal_mass
#' @param days_to_birth Number of days until birth, assuming a 365-day gestation period (d)
#' @param mother_length Body length of the mother (m)
#' @param bbc Body condition, as defined by Christiansen et al. (2022). Defaults to 0 for an individual of average condition.
#' @param body_density Average body density (kg/m^3)
#' @note In this parameterization, birth corresponds to t=0 and conception corresponds to t=-365
fetal_mass <- function(days_to_birth, mother_length, bbc = 0L, body_density = 805.07) {
    .Call('_narwind_fetal_mass', PACKAGE = 'narwind', days_to_birth, mother_length, bbc, body_density)
}

#' Fetal mass 
#' @name fetal_mass (vectorised)
#' @param days_to_birth Number of days until birth, assuming a 365-day gestation period (d)
#' @param mother_length Body length of the mother (m)
#' @param bbc Body condition, as defined by Christiansen et al. (2022). Defaults to 0 for an individual of average condition.
#' @param body_density Average body density (kg/m^3)
#' @note In this parameterization, birth corresponds to t=0 and conception corresponds to t=-365
fetal_mass_vec <- function(days_to_birth, mother_length, bbc = 0L, body_density = 805.07) {
    .Call('_narwind_fetal_mass_vec', PACKAGE = 'narwind', days_to_birth, mother_length, bbc, body_density)
}

#' Fetal length 
#' @name fetal_length
#' @param days_to_birth Number of days until birth, assuming a 365-day gestation period (d)
#' @param mother_length Body length of the mother (m)
#' @note In this parameterization, birth corresponds to t=0 and conception corresponds to t=-365
fetal_length <- function(days_to_birth, mother_length) {
    .Call('_narwind_fetal_length', PACKAGE = 'narwind', days_to_birth, mother_length)
}

#' Fetal length (vectorised)
#' @name fetal_length
#' @param days_to_birth Number of days until birth, assuming a 365-day gestation period (d)
#' @param mother_length Body length of the mother (m)
#' @note In this parameterization, birth corresponds to t=0 and conception corresponds to t=-365
fetal_length_vec <- function(days_to_birth, mother_length) {
    .Call('_narwind_fetal_length_vec', PACKAGE = 'narwind', days_to_birth, mother_length)
}

growth_cost <- function(leanmass_increment, EDens_lipids, EDens_protein, lipid_in_muscle, lipid_in_viscera, lipid_in_bones, protein_in_muscle, protein_in_viscera, protein_in_bones, prop_muscle, prop_viscera, prop_bones) {
    .Call('_narwind_growth_cost', PACKAGE = 'narwind', leanmass_increment, EDens_lipids, EDens_protein, lipid_in_muscle, lipid_in_viscera, lipid_in_bones, protein_in_muscle, protein_in_viscera, protein_in_bones, prop_muscle, prop_viscera, prop_bones)
}

add_calf <- function(n, attr, sex, nonreprod) {
    .Call('_narwind_add_calf', PACKAGE = 'narwind', n, attr, sex, nonreprod)
}

pleave <- function(now, enter, cohortID, factor, resid) {
    .Call('_narwind_pleave', PACKAGE = 'narwind', now, enter, cohortID, factor, resid)
}

entanglement_effect <- function(prob_survival, severity, ndays, entgl_hit) {
    .Call('_narwind_entanglement_effect', PACKAGE = 'narwind', prob_survival, severity, ndays, entgl_hit)
}

survival <- function(age, regime, female) {
    .Call('_narwind_survival', PACKAGE = 'narwind', age, regime, female)
}

clamp <- function(v, threshold) {
    .Call('_narwind_clamp', PACKAGE = 'narwind', v, threshold)
}

create_hash <- function(x0, y0, x1, y1) {
    .Call('_narwind_create_hash', PACKAGE = 'narwind', x0, y0, x1, y1)
}

geoD <- function(mat, x0, y0, x1, y1, limits, resolution) {
    .Call('_narwind_geoD', PACKAGE = 'narwind', mat, x0, y0, x1, y1, limits, resolution)
}

geoDist <- function(mat, x0, y0, x1, y1, limits, resolution, r) {
    .Call('_narwind_geoDist', PACKAGE = 'narwind', mat, x0, y0, x1, y1, limits, resolution, r)
}

#' Simulate right whale movements
#' @name NARW_simulator
#' @param densities array of density maps, stored in column-major order with 
#' indices [xind, yind, map] for projected spaces (xind is index for a projected lon coordinate, 
#' yind is index for a projected lat)
#' @param densitySeq 1-indexed vector specifying which density maps should be
#' used to simulate movement at each timepoint; number of timepoints to
#' simulate comes from length of vector densitySeq
#' @param latentDensitySeq 1-indexed vector specifying which density maps should be used to simulate movement for each latent animal
#' @param limits vector (xmin, xmax, ymin, ymax) of spatial coordinate extents for spatial densities
#' @param resolution vector (xres, yres) of spatial step sizes for spatial densities
#' @param M Number of proposals used in the importance sampler for movement (Michelot, 2019)
#' @param stepsize Radius of the proposal circle for movement (Michelot, 2019)
#' @param xinit matrix of initial x coordinates for latent animals (nlatent x n)
#' @param yinit matrix of initial y coordinates for latent animals (nlatent x n)
#' @return List of coordinates
NARW_simulator <- function(cohortID, seus, gsl, support, densities, densities_seus, densities_gsl, densities_gom, densitySeq, prey, fishing, vessels, noise, doseresp_seed, doseresp, regions, limits, limits_regions, limits_prey, limits_fishing, limits_vessels, limits_noise, resolution, resolution_regions, resolution_prey, resolution_fishing, resolution_vessels, resolution_noise, M, xinit, yinit, stressors, growth, prey_scale, starvation_coefs, starvation_death, starvation_onset, nursing_cessation, piling_hrs, progress) {
    .Call('_narwind_NARW_simulator', PACKAGE = 'narwind', cohortID, seus, gsl, support, densities, densities_seus, densities_gsl, densities_gom, densitySeq, prey, fishing, vessels, noise, doseresp_seed, doseresp, regions, limits, limits_regions, limits_prey, limits_fishing, limits_vessels, limits_noise, resolution, resolution_regions, resolution_prey, resolution_fishing, resolution_vessels, resolution_noise, M, xinit, yinit, stressors, growth, prey_scale, starvation_coefs, starvation_death, starvation_onset, nursing_cessation, piling_hrs, progress)
}

evalEnvironment <- function(density, density_seus, density_gsl, density_gom, prey, fishing, vessels, noise, regions, limits, limits_regions, limits_prey, limits_fishing, limits_vessels, limits_noise, resolution, resolution_regions, resolution_prey, resolution_fishing, resolution_vessels, resolution_noise, x, y, layer) {
    .Call('_narwind_evalEnvironment', PACKAGE = 'narwind', density, density_seus, density_gsl, density_gom, prey, fishing, vessels, noise, regions, limits, limits_regions, limits_prey, limits_fishing, limits_vessels, limits_noise, resolution, resolution_regions, resolution_prey, resolution_fishing, resolution_vessels, resolution_noise, x, y, layer)
}

