# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Random deviate from a truncated Normal distribution
NULL

#' Initialize age
#' @name start_age
NULL

#' Entanglement event
#' @name entanglement_event
NULL

#' Mouth-width-to-length ratio
#' @name start_mouth
NULL

#' Initialize body condition
#' @name start_bcondition
NULL

#' Initialize body condition
NULL

#' Age to length conversion
#' @name age2length
NULL

#' Incidence of foraging behavior
#' @name feeding_threshold
NULL

#' Variation in feeding/suckling effort with body condition
#'  @name scale_effort
NULL

#' Convert degrees to radians
NULL

#' Area of the gape
#' @name gape_size
NULL

#' Energy content of the prey
#' @name Econtent_cop
NULL

#' Filtration rate
#' @name filtration_rate
NULL

#' Milk ingestion rate
#' @name milk_ingestion
NULL

#' Milk assimilation efficiency
#' @name milk_assimilation
NULL

#' Milk provisioning
#' @name milk_supply
NULL

#' Total mass of mammary glands
#' @name mammary_mass
NULL

#' Milk production rate
#' @name milk_production
NULL

#' Resting metabolic rate
#' @name RMR
NULL

#' Costs of locomotion
#' @name locomotor_costs
NULL

#' Energetic cost of placental maintenance during pregnancy
#' @name placental_maintenance
NULL

#' Heat increment of gestation
#' @name heat_gestation
NULL

#' Fetal tissue mass
#' @name fetal_tissue_mass
NULL

#' Fetal blubber mass
#' @name fetal_blubber_mass
NULL

#' Fetal mass 
#' @name fetal_mass
NULL

#' Fetal length 
#' @name fetal_length
NULL

#' Energetic cost of growth
#' @name growth_cost
NULL

transpose_c <- function(m, k) {
    .Call('_narwind_transpose_c', PACKAGE = 'narwind', m, k)
}

multinomial <- function(probs) {
    .Call('_narwind_multinomial', PACKAGE = 'narwind', probs)
}

random_int <- function(n, lwr = 0L, uppr = 3L) {
    .Call('_narwind_random_int', PACKAGE = 'narwind', n, lwr, uppr)
}

random_multivariate_normal <- function(mu, Sigma) {
    .Call('_narwind_random_multivariate_normal', PACKAGE = 'narwind', mu, Sigma)
}

prob_migration <- function(n, destination, cohortID) {
    .Call('_narwind_prob_migration', PACKAGE = 'narwind', n, destination, cohortID)
}

response_threshold <- function(db) {
    .Call('_narwind_response_threshold', PACKAGE = 'narwind', db)
}

#' Random deviate from a truncated Normal distribution
#' 
#' @param location Location parameter
#' @param scale Scale parameter
#' @param L Lower bound
#' @param U Upper bound
rtnorm <- function(location, scale, L, U) {
    .Call('_narwind_rtnorm', PACKAGE = 'narwind', location, scale, L, U)
}

rtnorm_vec <- function(n, location, scale, L, U) {
    .Call('_narwind_rtnorm_vec', PACKAGE = 'narwind', n, location, scale, L, U)
}

start_age <- function(cohort) {
    .Call('_narwind_start_age', PACKAGE = 'narwind', cohort)
}

start_age_vec <- function(cohort) {
    .Call('_narwind_start_age_vec', PACKAGE = 'narwind', cohort)
}

entanglement_event <- function(p_entangled = 0, p_anterior = 0.732, p_severity = as.numeric( c(0.761, 0.155, 0.084))) {
    .Call('_narwind_entanglement_event', PACKAGE = 'narwind', p_entangled, p_anterior, p_severity)
}

start_mouth <- function(cohort, age) {
    .Call('_narwind_start_mouth', PACKAGE = 'narwind', cohort, age)
}

start_bcondition <- function(cohort, month = 10L, max_bc = 0.6) {
    .Call('_narwind_start_bcondition', PACKAGE = 'narwind', cohort, month, max_bc)
}

start_bcondition_vec <- function(cohort, month = 10L, max_bc = 0.6) {
    .Call('_narwind_start_bcondition_vec', PACKAGE = 'narwind', cohort, month, max_bc)
}

agL <- function(age, n = 1L, sd = FALSE) {
    .Call('_narwind_agL', PACKAGE = 'narwind', age, n, sd)
}

agL_vec <- function(age, sd = FALSE) {
    .Call('_narwind_agL_vec', PACKAGE = 'narwind', age, sd)
}

age2length <- function(age, gompertz) {
    .Call('_narwind_age2length', PACKAGE = 'narwind', age, gompertz)
}

age2length_vec <- function(age) {
    .Call('_narwind_age2length_vec', PACKAGE = 'narwind', age)
}

create_mat <- function() {
    .Call('_narwind_create_mat', PACKAGE = 'narwind')
}

mL <- function(n = 1L, sd = FALSE) {
    .Call('_narwind_mL', PACKAGE = 'narwind', n, sd)
}

length2mass <- function(L, param, lean = 0.5435686) {
    .Call('_narwind_length2mass', PACKAGE = 'narwind', L, param, lean)
}

length2mass_vec <- function(L, lean = 0.5435686) {
    .Call('_narwind_length2mass_vec', PACKAGE = 'narwind', L, lean)
}

increment_cohort <- function(cohort, age, female, rest, abort) {
    .Call('_narwind_increment_cohort', PACKAGE = 'narwind', cohort, age, female, rest, abort)
}

feeding_threshold <- function(min_prey, D) {
    .Call('_narwind_feeding_threshold', PACKAGE = 'narwind', min_prey, D)
}

scale_effort <- function(x, A, D, B, C, S) {
    .Call('_narwind_scale_effort', PACKAGE = 'narwind', x, A, D, B, C, S)
}

scale_effort_vec <- function(x, A, D, B, C, S) {
    .Call('_narwind_scale_effort_vec', PACKAGE = 'narwind', x, A, D, B, C, S)
}

deg2radians <- function(angle) {
    .Call('_narwind_deg2radians', PACKAGE = 'narwind', angle)
}

gape_size <- function(L, omega, alpha) {
    .Call('_narwind_gape_size', PACKAGE = 'narwind', L, omega, alpha)
}

Econtent_cop <- function(m, rho, E_digest, E_hif) {
    .Call('_narwind_Econtent_cop', PACKAGE = 'narwind', m, rho, E_digest, E_hif)
}

filtration_rate <- function(A, lambda_gape, V, E_capt, lambda_capt) {
    .Call('_narwind_filtration_rate', PACKAGE = 'narwind', A, lambda_gape, V, E_capt, lambda_capt)
}

milk_ingestion <- function(E_milk, M, E_gland, mu_female, delta_female, D) {
    .Call('_narwind_milk_ingestion', PACKAGE = 'narwind', E_milk, M, E_gland, mu_female, delta_female, D)
}

milk_assimilation <- function(t, T_lac, a, zeta) {
    .Call('_narwind_milk_assimilation', PACKAGE = 'narwind', t, T_lac, a, zeta)
}

milk_supply <- function(kappa, target_condition, M, R, zeta) {
    .Call('_narwind_milk_supply', PACKAGE = 'narwind', kappa, target_condition, M, R, zeta)
}

mammary_mass <- function(M) {
    .Call('_narwind_mammary_mass', PACKAGE = 'narwind', M)
}

milk_production <- function(m) {
    .Call('_narwind_milk_production', PACKAGE = 'narwind', m)
}

RMR <- function(M) {
    .Call('_narwind_RMR', PACKAGE = 'narwind', M)
}

locomotor_costs <- function(mass, strokerate_foraging, strokerate, glide_foraging, glide, t_feed, t_activ, scalar) {
    .Call('_narwind_locomotor_costs', PACKAGE = 'narwind', mass, strokerate_foraging, strokerate, glide_foraging, glide, t_feed, t_activ, scalar)
}

placental_maintenance <- function(G) {
    .Call('_narwind_placental_maintenance', PACKAGE = 'narwind', G)
}

heat_gestation <- function(birth_mass, delta_m) {
    .Call('_narwind_heat_gestation', PACKAGE = 'narwind', birth_mass, delta_m)
}

fetal_tissue_mass <- function(P_b, L) {
    .Call('_narwind_fetal_tissue_mass', PACKAGE = 'narwind', P_b, L)
}

fetal_blubber_mass <- function(L, M_muscle, M_viscera, M_bones, D_blubber, D_muscle, D_viscera, D_bones) {
    .Call('_narwind_fetal_blubber_mass', PACKAGE = 'narwind', L, M_muscle, M_viscera, M_bones, D_blubber, D_muscle, D_viscera, D_bones)
}

fetal_mass <- function(days_to_birth, mother_length, bbc = 0L, body_density = 805.07) {
    .Call('_narwind_fetal_mass', PACKAGE = 'narwind', days_to_birth, mother_length, bbc, body_density)
}

fetal_length <- function(days_to_birth, mother_length) {
    .Call('_narwind_fetal_length', PACKAGE = 'narwind', days_to_birth, mother_length)
}

growth_cost_old <- function(delta_m, prop_blubber, prop_water, P_lipid_blubber, rho_lipid, rho_protein, D_lipid, D_protein) {
    .Call('_narwind_growth_cost_old', PACKAGE = 'narwind', delta_m, prop_blubber, prop_water, P_lipid_blubber, rho_lipid, rho_protein, D_lipid, D_protein)
}

growth_cost <- function(mass_increment, EDens_lipids, EDens_protein, lipid_in_blubber, lipid_in_muscle, lipid_in_viscera, lipid_in_bones, protein_in_blubber, protein_in_muscle, protein_in_viscera, protein_in_bones, prop_blubber, prop_muscle, prop_viscera, prop_bones) {
    .Call('_narwind_growth_cost', PACKAGE = 'narwind', mass_increment, EDens_lipids, EDens_protein, lipid_in_blubber, lipid_in_muscle, lipid_in_viscera, lipid_in_bones, protein_in_blubber, protein_in_muscle, protein_in_viscera, protein_in_bones, prop_blubber, prop_muscle, prop_viscera, prop_bones)
}

add_calf <- function(n, attr) {
    .Call('_narwind_add_calf', PACKAGE = 'narwind', n, attr)
}

findminval <- function(num1, num2) {
    .Call('_narwind_findminval', PACKAGE = 'narwind', num1, num2)
}

pbirth <- function(now, enter, timespan = 60L) {
    .Call('_narwind_pbirth', PACKAGE = 'narwind', now, enter, timespan)
}

create_hash <- function(x0, y0, x1, y1) {
    .Call('_narwind_create_hash', PACKAGE = 'narwind', x0, y0, x1, y1)
}

geoD <- function(mat, x0, y0, x1, y1, limits, resolution) {
    .Call('_narwind_geoD', PACKAGE = 'narwind', mat, x0, y0, x1, y1, limits, resolution)
}

geoDist <- function(mat, x0, y0, x1, y1, limits, resolution, r) {
    .Call('_narwind_geoDist', PACKAGE = 'narwind', mat, x0, y0, x1, y1, limits, resolution, r)
}

#' Simulate right whale movements
NULL

NARW_simulator <- function(cohortID, seus, gsl, support, densities, densities_seus, densities_gsl, densitySeq, latentDensitySeq, prey, fishing, vessels, noise, doseresp, daylight, regions, limits, resolution, M, stepsize, xinit, yinit, stressors, growth, starvation, progress) {
    .Call('_narwind_NARW_simulator', PACKAGE = 'narwind', cohortID, seus, gsl, support, densities, densities_seus, densities_gsl, densitySeq, latentDensitySeq, prey, fishing, vessels, noise, doseresp, daylight, regions, limits, resolution, M, stepsize, xinit, yinit, stressors, growth, starvation, progress)
}

evalEnvironment <- function(density, density_seus, density_gsl, prey, fishing, vessels, noise, daylight, regions, limits, resolution, x, y, layer) {
    .Call('_narwind_evalEnvironment', PACKAGE = 'narwind', density, density_seus, density_gsl, prey, fishing, vessels, noise, daylight, regions, limits, resolution, x, y, layer)
}

