# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simBasic <- function(t, n, cov1, cov2, beta, lim, res, allr) {
    .Call(`_narwind_simBasic`, t, n, cov1, cov2, beta, lim, res, allr)
}

simAnnual <- function(densities, densitySeq, limits, resolution, M, stepsize, xinit, yinit) {
    .Call(`_narwind_simAnnual`, densities, densitySeq, limits, resolution, M, stepsize, xinit, yinit)
}

simAnnualCoupled <- function(densities, densitySeq, latentDensitySeq, limits, resolution, M, stepsize, xinit, yinit) {
    .Call(`_narwind_simAnnualCoupled`, densities, densitySeq, latentDensitySeq, limits, resolution, M, stepsize, xinit, yinit)
}

evalEnvironment <- function(density, limits, resolution, x, y) {
    .Call(`_narwind_evalEnvironment`, density, limits, resolution, x, y)
}

